routes/web.php
<?php

use App\Http\Controllers\TaskController;
use App\Http\Controllers\TimeSheetController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::group(['middleware' => ['auth']], function () {

    Route::get('profile', [UserController::class, 'profile'])->name('profile');
    Route::get('reset-password', [UserController::class, 'resetPasswordForm']);
    Route::post('password-update', [UserController::class, 'passwordUpdate']);

    Route::resource('tasks', TaskController::class);
    Route::post('changeTaskStatus', [TaskController::class, 'changeTaskStatus'])->name('changeTaskStatus');



    ################## Start:: Admin #################
    Route::group(['middleware' => ['isAdmin']], function () {
        Route::get('users', [UserController::class, 'userLists']);
        Route::post('users', [UserController::class, 'userLists']);
        Route::post('changeUserStatus', [UserController::class, 'changeUserStatus'])->name('changeUserStatus');
        Route::delete('user-delete/{id}', [UserController::class, 'userDelete'])->name('user.delete');

        ### Start: TimeSheet
        Route::get('timesheet', [TimeSheetController::class, 'index'])->name('timesheet.index');
        Route::get('timesheet/create', [TimeSheetController::class, 'create'])->name('timesheet.create');
        Route::post('timesheet/store', [TimeSheetController::class, 'store'])->name('timesheet.store');
        Route::get('timesheet/store/{id}/edit/', [TimeSheetController::class, 'edit'])->name('timesheet.edit');
        Route::put('timesheet/store/update/{id}', [TimeSheetController::class, 'update'])->name('timesheet.update');
        Route::delete('timesheet/delete/{id}', [TimeSheetController::class, 'delete'])->name('timesheet.delete');
        ### End: TimeSheet

    });
    ################## End:: Admin #################
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->belongsTo(User::class, 'assigned_user_id', 'id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function tasks()
    {
        return $this->hasMany(Task::class, 'assigned_user_id', 'id');
    }

    public function timesheets()
    {
        return $this->hasMany(TimeSheet::class, 'user_id', 'id');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use App\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $status = $request->status;
        $data['tasks'] = Task::where(function ($q) use ($status){
            if ($status || $status == "0"){
                $q->whereStatus($status);
            }
        });
        if(Auth::user()->role_as == 1){
            $data['tasks'] = $data['tasks']->whereUserId(Auth::user()->id)->paginate(10);
        }else{
            $data['tasks'] = $data['tasks']->where('assigned_user_id', Auth::user()->id)->paginate(10);
        }

        $data['users'] = User::all();
        return view('user.task.list')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['users'] = User::all();
        return view('user.task.create')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        $validator = Validator::make($request->all(), [
//            'description' => 'required',
//            'status' => 'required'
//        ]);
//
//        if ($validator->fails()) {
//            return redirect()->back()->withErrors($validator)->withInput();
//        }
        $user = User::find(Auth::user()->id);
        $task = new Task();
        $task->user_id = Auth::user()->id;
        $task->description = $request->description;
        $task->status = $request->status ?? $request->admin_status;
        if ($user->role_as == 0){
            $task->assigned_user_id = Auth::user()->id;
        }else{
            $task->assigned_user_id = $request->assigned_user_id;
        }

        $task->save();

        return redirect()->route('tasks.index')->with('success', 'Task Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::find($id);
        $task->delete();

        return redirect()->back()->with('success', 'Deleted Successfully');
    }

    public function changeTaskStatus(Request $request): JsonResponse
    {
        $user = Task::find($request->id);
        $user->status = $request->status;
        $user->save();

        return response()->json([
            'data' => 'success',
        ]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\TimeSheet;
use App\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    public function profile()
    {
        $data['user'] = User::find(Auth::user()->id);
        $data['user_info'] =  User::withCount([
            'timesheets as total_worked_duration' => function ($query) {
                $query->select(DB::raw("SUM(duration) as total"));
            },
            'timesheets as total_pay' => function ($query) {
                $query->select(DB::raw("SUM(total_pay) as total_pay"));
            },
            'tasks as total_task_count' => function ($query) {
                $query->select(DB::raw("COUNT(id) as total_task_count"));
            }

        ])->whereId(Auth::user()->id)->first();

        return view('user.profile')->with($data);
    }

    public function userLists(Request $request)
    {
        $status = $request->status;
        $data['users'] = User::where(function ($q) use ($status){
            if ($status || $status == "0"){
                $q->whereStatus($status);
            }
        })->paginate(10);

        return view('user.users')->with($data);
    }

    public function userDelete($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect()->back()->with('success', 'User Deleted Successfully');
    }

    public function resetPasswordForm()
    {
        return view('user.reset-password');
    }

    public function passwordUpdate(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'new_password'   => 'required|min:6',
            'confirm_password' => 'required|min:6'
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $user = Auth::user();

        if ($request->new_password === $request->confirm_password) {
            $user->password = Hash::make($request->new_password);
            $user->save();
            return redirect()->back()->with('success', 'Updated password');
        } else {
            return back()->with('error', 'Password and confirm password not matched');
        }
    }

    public function changeUserStatus(Request $request): JsonResponse
    {
        $user = User::find($request->id);
        $user->status = $request->status;
        $user->save();

        return response()->json([
            'data' => 'success',
        ]);
    }

}

resources/views/user/task/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2 class="text-center">Add Task</h2>
        <form action="{{ route('tasks.store') }}" method="post">
        @csrf
            <label class="task"><b>Task Description</b></label>
            <br>
            <textarea name="description" id="task" cols="30" rows="5" class="form-control" required></textarea>
            <br>
            @if(\Illuminate\Support\Facades\Auth::user()->role_as == 1)
            <label for=""><b>Task for</b></label>
            <select name="assigned_user_id" id="status" class="form-control form-control-solid form-control-md">
                <option value="">--Select user--</option>
                @foreach(@$users as $user)
                    <option value="{{ @$user->id }}">{{ @$user->name }}</option>
                @endforeach
            </select>
            <br>
            @endif
            <label for="status"><b>Status</b></label>
            <select name="status" id="status"
                    class="form-control form-control-solid form-control-md" required>
                <option value="">--Select Status--</option>
                <option value="0">Private</option>
                <option value="1">Public</option>
                @if(\Illuminate\Support\Facades\Auth::user()->role_as == 1)
                    <option value="2">Admin & Assigned User</option>
                @endif
            </select>
            <br>
            <input type="submit" class="btn btn-primary"></input>
        </form>
    </div>

@endsection

resources/views/user/task/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>My Task List</h2>
        <div class="row align-items-center d-flex">
            <div class="col-md-8">
                <form method="get" action="{{url()->current()}}">
                    <div class="card-title align-items-center flex-row d-flex">
                        <span>
                    <div>
                        <p class="m-0 d-block text-dark font-weight-bolder">Filter by:</p>
                    </div>
                </span>
                <span class="ml-4">
                    <select name="status" class="form-control form-control-solid form-control-md">
                        <option value="">--select status--</option>
                        <option value="0" @if(app('request')->status == "0") selected @endif>Private</option>
                        <option value="1" @if(app('request')->status == 1) selected @endif>Public</option>
                        @if(\Illuminate\Support\Facades\Auth::user()->role_as == 1)
                        <option value="2" @if(app('request')->status == 2) selected @endif>Admin & Assigned User</option>
                        @endif
                    </select>
                </span>
                <span class="ml-4">
                    <button type="submit" class="btn btn-primary filter-search-btn"><i class="fas fa-search"></i> Search</button>
                </span>
                    </div>
                </form>
            </div>
            <div class="col-md-4">
                <a href="{{ route('tasks.create') }}" class="btn btn-primary"><i class="fas fa-plus"></i> Add Task</a>
            </div>
        </div>

        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Sl No</th>
                @if(\Illuminate\Support\Facades\Auth::user()->role_as == 1)
                <th>Task Assigned User</th>
                @endif
                <th scope="col">Task Description</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @forelse(@$tasks as $task)
            <tr>
                <th> {{ @$loop->iteration }}</th>
                @if(\Illuminate\Support\Facades\Auth::user()->role_as == 1)
                <td>
                    @foreach(@$users as $user)
                        @if(@$user->id == @$task->assigned_user_id)
                            {{ @$user->name }}
                        @endif
                    @endforeach
                </td>
                @endif
                <td>{{ @$task->description }}</td>
                <td>
                    <span id="hidden_task_id" style="display: none">{{@$task->id}}</span>
                    <select name="status" class="status label-inline font-weight-bolder mb-1 badge badge-info">
                        <option value="0" @if(@$task->status == 0) selected @endif>Private</option>
                        <option value="1" @if(@$task->status == 1) selected @endif>Public</option>
                         {{-- @if(\Illuminate\Support\Facades\Auth::user()->role_as == 1) --}}
                            <option value="2" @if(@$task->status == 2) selected @endif>Admin & Assigned User</option>
                        {{--      @endif--}}

                    </select>
                </td>
                <td>
                    <form action="{{route('tasks.destroy', @$task->id)}}" method="post">
                        <input type="hidden" name="_method" value="DELETE">
                        @csrf
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure to delete?')" >
                            <i class="fa fa-trash"></i>
                        </button>
                    </form>
                </td>
            </tr
            @empty
            <tr><td colspan="4" class="text-center">NO TASK FOUND</td></tr>
            @endforelse
            </tbody>
        </table>
        {{ $tasks->links('pagination::bootstrap-4') }}
    </div>
@endsection

@section('script')
    <script>
        $(".status").change(function () {
            var id = $(this).closest('tr').find('#hidden_task_id').html();
            var status_value = $(this).closest('tr').find('.status option:selected').val();
            console.log(id, status_value)
            $.ajax({
                url: "{{route('changeTaskStatus')}}",
                type: "POST",
                data: {"status": status_value, "id": id, "_token": "{{ csrf_token() }}",},
                success: function(response){ // What to do if we succeed
                    if(response.data == 'success'){
                        toastr.success("Task status has been changed");
                    } else{
                        toastr.error("Task status can not change")
                    }
                }
            });
        });
    </script>
@endsection