routes/web.php
<?php

use App\Http\Controllers\TaskController;
use App\Http\Controllers\TimeSheetController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::group(['middleware' => ['auth']], function () {

    Route::get('profile', [UserController::class, 'profile'])->name('profile');
    Route::get('reset-password', [UserController::class, 'resetPasswordForm']);
    Route::post('password-update', [UserController::class, 'passwordUpdate']);

    Route::resource('tasks', TaskController::class);
    Route::post('changeTaskStatus', [TaskController::class, 'changeTaskStatus'])->name('changeTaskStatus');



    ################## Start:: Admin #################
    Route::group(['middleware' => ['isAdmin']], function () {
        Route::get('users', [UserController::class, 'userLists']);
        Route::post('users', [UserController::class, 'userLists']);
        Route::post('changeUserStatus', [UserController::class, 'changeUserStatus'])->name('changeUserStatus');
        Route::delete('user-delete/{id}', [UserController::class, 'userDelete'])->name('user.delete');

        ### Start: TimeSheet
        Route::get('timesheet', [TimeSheetController::class, 'index'])->name('timesheet.index');
        Route::get('timesheet/create', [TimeSheetController::class, 'create'])->name('timesheet.create');
        Route::post('timesheet/store', [TimeSheetController::class, 'store'])->name('timesheet.store');
        Route::get('timesheet/store/{id}/edit/', [TimeSheetController::class, 'edit'])->name('timesheet.edit');
        Route::put('timesheet/store/update/{id}', [TimeSheetController::class, 'update'])->name('timesheet.update');
        Route::delete('timesheet/delete/{id}', [TimeSheetController::class, 'delete'])->name('timesheet.delete');
        ### End: TimeSheet

    });
    ################## End:: Admin #################
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <script src="{{ asset('assets/js/fontawesome.js') }}"></script>

    <!-- Styles -->
{{--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">--}}
    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}" integrity="" crossorigin="anonymous">


{{--        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">--}}

    <!--Start:: Toastr -->
    <link href="{{ asset('assets/cloudflare/ajax/libs/bootstrap/bootstrap.css') }}" rel="stylesheet">
    <script src="{{ asset('assets/ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/cloudflare/ajax/libs/toastr/toastr.min.css') }}">
    <script src="{{ asset('assets/cloudflare/ajax/libs/toastr/toastr.min.js') }}"></script>
    <!--End:: Toastr -->

    <!--Start:: Datetime  -->
{{--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">--}}
    <link rel="stylesheet" href="{{ asset('assets/cloudflare/ajax/libs/bootstrapMin/bootstrap.min.css') }}">
{{--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">--}}
    <link rel="stylesheet" href="{{ asset('assets/cloudflare/ajax/libs/bootstrapMin/bootstrap-datetimepicker.min.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('assets/icon/bootstrap.min.css') }}">
    <!--End:: Datetime -->

</head>
<body>
    <div id="app">
        @include('layouts.navbar')

        <div class="container">
            <main class="py-4">
                @yield('content')
            </main>
        </div>

    </div>
    @yield('script')
    <script>
        @if(Session::has('success'))
            toastr.options =
            {
                "closeButton" : true,
                "progressBar" : true
            }
            toastr.success("{{ session('success') }}");
        @endif

        @if(Session::has('error'))
            toastr.options =
            {
                "closeButton" : true,
                "progressBar" : true
            }
            toastr.error("{{ session('error') }}");
        @endif

        @if(Session::has('info'))
            toastr.options =
            {
                "closeButton" : true,
                "progressBar" : true
            }
            toastr.info("{{ session('info') }}");
        @endif

        @if(Session::has('warning'))
            toastr.options =
            {
                "closeButton" : true,
                "progressBar" : true
            }
            toastr.warning("{{ session('warning') }}");
        @endif
    </script>
    <script src="{{ asset('assets/js/jquery-3.5.0.min.js') }}"></script>
    <script src="{{ asset('assets/cloudflare/ajax/libs/popper/popper.min.js') }}" integrity="" crossorigin="anonymous"></script>
    <script src="{{ asset('assets/js/bootstrap.min.js') }}" integrity="" crossorigin="anonymous"></script>

    <!--Start:: Datetime Picker -->

    <script src="{{ asset('assets/cloudflare/ajax/libs/datetime/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/cloudflare/ajax/libs/datetime/moment.min.js') }}"></script>
    <script src="{{ asset('assets/cloudflare/ajax/libs/datetime/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/cloudflare/ajax/libs/datetime/datetimepicker.min.js') }}"></script>

    <!--End:: Datetime Picker -->
    <script type="text/javascript">
        $(function() {
            $('#datetimepicker').datetimepicker();
        });
    </script>
    <script type="text/javascript">
        $(function() {
            $('#datetimepicker2').datetimepicker();
        });
    </script>
</body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-md bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    @if (Route::has('login'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                    @endif

                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/') }}"><i class="fas fa-home"></i> Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('tasks.index') }}"><i class="fas fa-tasks"></i> My Task List</a>
                    </li>
                    @if(\Illuminate\Support\Facades\Auth::user()->role_as == 1)
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('timesheet.index') }}"><i class="fas fa-clock"></i> TimeSheet</a>
                        </li>
                    @endif

                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ url('profile') }}"><i class="fas fa-user"></i> My Profile</a>

                            @if(\Illuminate\Support\Facades\Auth::user()->role_as == 1)
                                <a class="dropdown-item" href="{{ url('users') }}"><i class="fas fa-users"></i> Users List</a>
                            @endif
                            <a class="dropdown-item" href="{{ url('reset-password') }}"><i class="fa fa-key" aria-hidden="true"></i> Reset Password</a>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                <i class="fa fa-sign-out" aria-hidden="true"></i> {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>